### ISSUE TITLE
important?

### ISSUE THREAD

**Issue by wooorm** [IIYAMA12/cssttr#4]
https://github.com/IIYAMA12/cssttr/blob/1c542eabef3140712e0f4a809dba336ef7c84e5c/css/main.css#L70

I think the important part isn’t needed, or is it?

**Comment by IIYAMA12** [comment]
It was indeed not need. It was only strange that the button element remains to have those original focus outlines. So I tried to force it away. Which seems to have no influence on them. It seems that I forgot to remove the !important afterwards.

Thanks!
