### ISSUE TITLE
CSS reset vs normalise

### ISSUE THREAD

**Issue by wooorm** [IIYAMA12/cssttr#5]
I saw you‘re using a CSS reset, and I’m wondering why you’re using that instead of something like normalise? https://github.com/necolas/normalize.css

**Comment by IIYAMA12** [comment]
I wasn't aware that it did exist.

**Will test it out!**

**Comment by IIYAMA12** [comment]
Nvm, not normalize enough for me. I prefer to annihilate the default styling.

**Comment by wooorm** [comment]
Even better!
