### ISSUE TITLE
Forced button height

### ISSUE THREAD

**Issue by wooorm** [IIYAMA12/cssttr#7]
Heya, I was wondering why you have a height specified on buttons:

https://github.com/IIYAMA12/cssttr/blob/1c542eabef3140712e0f4a809dba336ef7c84e5c/css/main.css#L55-L61

Why not use a bit of top/bottom padding? That makes it easier to center the text!

**Comment by IIYAMA12** [comment]
Because I do not want the text have influence over the button height.

**Comment by wooorm** [comment]
Wouldn’t padding make more sense?

**Comment by IIYAMA12** [comment]
How would you know then, if the font with the font-size: 1em; is taking exactly 1em height?

As there are 3 layers:
- Padding
- Font-size < variable based on the font.
- Padding (2)

I agree with you that it would make more sense when the buttons are able to overflow so it supports multiple lines, but for this design I prefer to lock it.

**Comment by wooorm** [comment]
Does it always need be exactly 2rem? What if the font is bigger?

First, height doesn't work on inline elements (i think buttons are by default inline, unless you change it). which is weird: some buttons will turn 2rem height, others won't.

Second, you could get the same result with padding or height, right? maybe it’s a bit more math to make it exactly 2rem in height, but it could work, right?

Then, third, if it can be achieved both ways, why choose height which has the downside of wrapping across lines?
