### ISSUE TITLE
Vendor prefixes

### ISSUE THREAD

**Issue by wooorm** [IIYAMA12/cssttr#8]
I saw you added vendor prefixes to all box shadows. Have you thought about whether they’re needed?

https://github.com/IIYAMA12/cssttr/blob/1c542eabef3140712e0f4a809dba336ef7c84e5c/css/main.css#L165-L170

**Comment by IIYAMA12** [comment]
Yes, I am well aware what they are for. I am using a quick shadow generator to make the set and considered them as a takeaway. The only thing I am not a aware of, is if they have much impact on the performance. 

https://css-tricks.com/do-we-need-box-shadow-prefixes/

**Comment by wooorm** [comment]
Interesting!
